name: task_management
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  cached_network_image: ^3.4.1
  get_storage: ^2.1.1
  connectivity_plus: ^6.1.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
